services:
  paseto-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paseto-web
    ports:
      - "127.0.0.1:6066:8080"
    environment:
      - PORT=8080
      - CORS_ORIGIN=https://paseto.getgud.boo
    restart: unless-stopped
